/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterM;

import Model.ConnectionSQLdb;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcelle F
 */
public class Courses extends javax.swing.JPanel {

    /**
     * Creates new form Cursos
     */
public void loadTableData() {
    // Configuración del modelo
    DefaultTableModel model = (DefaultTableModel) TblCursos.getModel();
    model.setRowCount(0); // Limpia los datos previos en la tabla

    // Consulta SQL: Verifica que los nombres coincidan con los de la base de datos
    String query = "SELECT Sigla, Nombre_curso, Modalidad, Area_especializacion, Cantidad_estudiantes FROM Cursos";

    try (Connection conn = new ConnectionSQLdb().getConnection();
         PreparedStatement stmt = conn.prepareStatement(query);
         ResultSet rs = stmt.executeQuery()) {

        while (rs.next()) {
            // Extrae los datos de cada fila de la consulta
            String sigla = rs.getString("Sigla");
            String nombreCurso = rs.getString("Nombre_curso");
            String modalidad = rs.getString("Modalidad");
            String areaEspecializacion = rs.getString("Area_especializacion");
            int cantidadEstudiantes = rs.getInt("Cantidad_estudiantes");

            // Agrega una nueva fila al modelo de la tabla
            model.addRow(new Object[]{sigla, nombreCurso, modalidad, areaEspecializacion, cantidadEstudiantes});
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.getMessage());
    }
}

public Courses() {
    initComponents();
    loadTableData(); // Llenar la tabla al inicializar
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelExpedient = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblCursos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(660, 480));
        setPreferredSize(new java.awt.Dimension(699, 529));

        panelExpedient.setBackground(new java.awt.Color(220, 241, 253));
        panelExpedient.setMaximumSize(new java.awt.Dimension(2147483647, 0));
        panelExpedient.setMinimumSize(new java.awt.Dimension(45, 0));
        panelExpedient.setPreferredSize(new java.awt.Dimension(570, 450));
        panelExpedient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sigla", "Nombre_curso", "Modalidad", "Area_especializacion", "Cantidad_estudiantes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblCursos);

        panelExpedient.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 530, 360));

        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel2.setText("Cursos Impartidos");
        panelExpedient.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelExpedient, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(panelExpedient, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TblCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblCursosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TblCursosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TblCursos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelExpedient;
    // End of variables declaration//GEN-END:variables
}
