/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfaW;

import javax.swing.SwingConstants;

/**
 *
 * @author wendy_6rrub
 */
public class CurrentCourses extends javax.swing.JPanel {

    /**
     * Creates new form CurrentCourses
     */
    public CurrentCourses() {
        initComponents();
        
        txtInfoCurrent.setText("<html>Aquí encontrarás la lista de cursos en los que "
                + "estás inscrito actualmente. Puedes consultar el estado de "
                + "cada curso, como fechas importantes, facilitadores y horarios "
                + "asignados</html>");
        txtInfoCurrent.setVerticalAlignment(SwingConstants.TOP); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content3 = new javax.swing.JPanel();
        lblStudentName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCurrent = new javax.swing.JTable();
        txtInfoCurrent = new javax.swing.JLabel();

        Content3.setBackground(new java.awt.Color(255, 255, 255));
        Content3.setPreferredSize(new java.awt.Dimension(709, 604));

        lblStudentName.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(0, 0, 51));
        lblStudentName.setText("¡Hola, Nombre!");

        tableCurrent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Curso", "Facilitador", "Horario", "Fecha de finalización"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCurrent.setAlignmentY(1.0F);
        jScrollPane1.setViewportView(tableCurrent);

        txtInfoCurrent.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtInfoCurrent.setForeground(new java.awt.Color(97, 57, 0));

        javax.swing.GroupLayout Content3Layout = new javax.swing.GroupLayout(Content3);
        Content3.setLayout(Content3Layout);
        Content3Layout.setHorizontalGroup(
            Content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Content3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(Content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInfoCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        Content3Layout.setVerticalGroup(
            Content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Content3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(txtInfoCurrent, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content3, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content3, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblStudentName;
    public javax.swing.JTable tableCurrent;
    private javax.swing.JLabel txtInfoCurrent;
    // End of variables declaration//GEN-END:variables
}
