/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfaW;

import java.awt.Color;

/**
 *
 * @author wendy_6rrub
 */
public class StudentExpedient extends javax.swing.JPanel {

    /**
     * Creates new form StudentExpedient
     */
    public StudentExpedient() {
        initComponents();
        
        if (panelExpedient != null) {
            //panel trasparente 
            panelExpedient.setBackground(new Color(84, 155, 226, 100));
            panelExpedient.setOpaque(true);}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelExpedient = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableExpe = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        panelExpedient.setBackground(new java.awt.Color(255, 255, 255));
        panelExpedient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableExpe.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        tableExpe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Curso", "Facilitador", "Modalidad", "Estado", "Fecha de finalización"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableExpe.setSelectionBackground(new java.awt.Color(130, 150, 187));
        jScrollPane1.setViewportView(tableExpe);

        panelExpedient.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 620, 360));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel2.setText("Cursos aprobados");
        panelExpedient.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExpedient, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelExpedient, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelExpedient;
    public javax.swing.JTable tableExpe;
    // End of variables declaration//GEN-END:variables
}
