/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfaW;

import javax.swing.SwingConstants;

/**
 *
 * @author wendy_6rrub
 */
public class StudentSchedule extends javax.swing.JPanel {

    /**
     * Creates new form StudentSchedule
     */
    public StudentSchedule() {
        initComponents();
        
        txtMonday8_9.setText("<html>Nombre largo del curso que se ajustará a varias líneas si es necesario</html>");
        txtMonday8_9.setVerticalAlignment(SwingConstants.TOP); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSchedule = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtMonday8_9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();

        panelSchedule.setBackground(new java.awt.Color(255, 255, 255));
        panelSchedule.setForeground(new java.awt.Color(51, 102, 0));
        panelSchedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("Lunes");
        panelSchedule.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText(" Martes");
        panelSchedule.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 0));
        jLabel3.setText("Miércoles");
        panelSchedule.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText(" Jueves");
        panelSchedule.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 0));
        jLabel5.setText("Viernes");
        panelSchedule.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 0));
        jLabel6.setText("05:00 pm");
        panelSchedule.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 0));
        jLabel7.setText("  8:00 am");
        panelSchedule.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 0));
        jLabel8.setText("  9:00 am");
        panelSchedule.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 0));
        jLabel9.setText("10:00 am");
        panelSchedule.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 0));
        jLabel10.setText("11:00 am");
        panelSchedule.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 102, 0));
        jLabel11.setText("12:00 pm");
        panelSchedule.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 102, 0));
        jLabel12.setText("01:00 pm");
        panelSchedule.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 102, 0));
        jLabel13.setText("02:00 pm");
        panelSchedule.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel14.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 102, 0));
        jLabel14.setText("03:00 pm");
        panelSchedule.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel15.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 102, 0));
        jLabel15.setText("04:00 pm");
        panelSchedule.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jLabel16.setText("jLabel16");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 110, 40));

        jLabel17.setBackground(new java.awt.Color(204, 255, 255));
        jLabel17.setForeground(new java.awt.Color(255, 204, 204));
        jLabel17.setText("jLabel16");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 110, 40));

        txtMonday8_9.setText("jLabel16");
        txtMonday8_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(txtMonday8_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 110, 40));

        jLabel19.setBackground(new java.awt.Color(204, 255, 255));
        jLabel19.setForeground(new java.awt.Color(255, 204, 204));
        jLabel19.setText("jLabel16");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 110, 40));

        jLabel20.setBackground(new java.awt.Color(204, 255, 255));
        jLabel20.setForeground(new java.awt.Color(255, 204, 204));
        jLabel20.setText("jLabel16");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 110, 40));

        jLabel21.setBackground(new java.awt.Color(204, 255, 255));
        jLabel21.setForeground(new java.awt.Color(255, 204, 204));
        jLabel21.setText("jLabel16");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 110, 40));

        jLabel22.setBackground(new java.awt.Color(204, 255, 255));
        jLabel22.setForeground(new java.awt.Color(255, 204, 204));
        jLabel22.setText("jLabel16");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 110, 40));

        jLabel23.setBackground(new java.awt.Color(204, 255, 255));
        jLabel23.setForeground(new java.awt.Color(255, 204, 204));
        jLabel23.setText("jLabel16");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 110, 40));

        jLabel24.setBackground(new java.awt.Color(204, 255, 255));
        jLabel24.setForeground(new java.awt.Color(255, 204, 204));
        jLabel24.setText("jLabel16");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 110, 40));

        jLabel25.setBackground(new java.awt.Color(204, 255, 255));
        jLabel25.setForeground(new java.awt.Color(255, 204, 204));
        jLabel25.setText("jLabel16");
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 110, 40));

        jLabel26.setText("jLabel16");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 110, 40));

        jLabel27.setBackground(new java.awt.Color(204, 255, 255));
        jLabel27.setForeground(new java.awt.Color(255, 204, 204));
        jLabel27.setText("jLabel16");
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 110, 40));

        jLabel28.setText("jLabel16");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 110, 40));

        jLabel29.setBackground(new java.awt.Color(204, 255, 255));
        jLabel29.setForeground(new java.awt.Color(255, 204, 204));
        jLabel29.setText("jLabel16");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 110, 40));

        jLabel30.setBackground(new java.awt.Color(204, 255, 255));
        jLabel30.setForeground(new java.awt.Color(255, 204, 204));
        jLabel30.setText("jLabel16");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 110, 40));

        jLabel31.setBackground(new java.awt.Color(204, 255, 255));
        jLabel31.setForeground(new java.awt.Color(255, 204, 204));
        jLabel31.setText("jLabel16");
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 110, 40));

        jLabel32.setBackground(new java.awt.Color(204, 255, 255));
        jLabel32.setForeground(new java.awt.Color(255, 204, 204));
        jLabel32.setText("jLabel16");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 110, 40));

        jLabel33.setBackground(new java.awt.Color(204, 255, 255));
        jLabel33.setForeground(new java.awt.Color(255, 204, 204));
        jLabel33.setText("jLabel16");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 110, 40));

        jLabel34.setBackground(new java.awt.Color(204, 255, 255));
        jLabel34.setForeground(new java.awt.Color(255, 204, 204));
        jLabel34.setText("jLabel16");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 110, 40));

        jLabel35.setBackground(new java.awt.Color(204, 255, 255));
        jLabel35.setForeground(new java.awt.Color(255, 204, 204));
        jLabel35.setText("jLabel16");
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 110, 40));

        jLabel36.setBackground(new java.awt.Color(204, 255, 255));
        jLabel36.setForeground(new java.awt.Color(255, 204, 204));
        jLabel36.setText("jLabel16");
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 110, 40));

        jLabel37.setBackground(new java.awt.Color(204, 255, 255));
        jLabel37.setForeground(new java.awt.Color(255, 204, 204));
        jLabel37.setText("jLabel16");
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 110, 40));

        jLabel38.setText("jLabel16");
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 110, 40));

        jLabel39.setBackground(new java.awt.Color(204, 255, 255));
        jLabel39.setForeground(new java.awt.Color(255, 204, 204));
        jLabel39.setText("jLabel16");
        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 110, 40));

        jLabel40.setBackground(new java.awt.Color(204, 255, 255));
        jLabel40.setForeground(new java.awt.Color(255, 204, 204));
        jLabel40.setText("jLabel16");
        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 110, 40));

        jLabel41.setBackground(new java.awt.Color(204, 255, 255));
        jLabel41.setForeground(new java.awt.Color(255, 204, 204));
        jLabel41.setText("jLabel16");
        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 110, 40));

        jLabel42.setBackground(new java.awt.Color(204, 255, 255));
        jLabel42.setForeground(new java.awt.Color(255, 204, 204));
        jLabel42.setText("jLabel16");
        jLabel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 110, 40));

        jLabel43.setBackground(new java.awt.Color(204, 255, 255));
        jLabel43.setForeground(new java.awt.Color(255, 204, 204));
        jLabel43.setText("jLabel16");
        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 110, 40));

        jLabel44.setBackground(new java.awt.Color(204, 255, 255));
        jLabel44.setForeground(new java.awt.Color(255, 204, 204));
        jLabel44.setText("jLabel16");
        jLabel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 110, 40));

        jLabel45.setText("jLabel16");
        jLabel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 110, 40));

        jLabel46.setBackground(new java.awt.Color(204, 255, 255));
        jLabel46.setForeground(new java.awt.Color(255, 204, 204));
        jLabel46.setText("jLabel16");
        jLabel46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 110, 40));

        jLabel47.setText("jLabel16");
        jLabel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 110, 40));

        jLabel48.setBackground(new java.awt.Color(204, 255, 255));
        jLabel48.setForeground(new java.awt.Color(255, 204, 204));
        jLabel48.setText("jLabel16");
        jLabel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 110, 40));

        jLabel49.setBackground(new java.awt.Color(204, 255, 255));
        jLabel49.setForeground(new java.awt.Color(255, 204, 204));
        jLabel49.setText("jLabel16");
        jLabel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 110, 40));

        jLabel50.setBackground(new java.awt.Color(204, 255, 255));
        jLabel50.setForeground(new java.awt.Color(255, 204, 204));
        jLabel50.setText("jLabel16");
        jLabel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 110, 40));

        jLabel51.setBackground(new java.awt.Color(204, 255, 255));
        jLabel51.setForeground(new java.awt.Color(255, 204, 204));
        jLabel51.setText("jLabel16");
        jLabel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 110, 40));

        jLabel52.setBackground(new java.awt.Color(204, 255, 255));
        jLabel52.setForeground(new java.awt.Color(255, 204, 204));
        jLabel52.setText("jLabel16");
        jLabel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 110, 40));

        jLabel53.setBackground(new java.awt.Color(204, 255, 255));
        jLabel53.setForeground(new java.awt.Color(255, 204, 204));
        jLabel53.setText("jLabel16");
        jLabel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 110, 40));

        jLabel54.setText("jLabel16");
        jLabel54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 110, 40));

        jLabel55.setBackground(new java.awt.Color(204, 255, 255));
        jLabel55.setForeground(new java.awt.Color(255, 204, 204));
        jLabel55.setText("jLabel16");
        jLabel55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 110, 40));

        jLabel56.setBackground(new java.awt.Color(204, 255, 255));
        jLabel56.setForeground(new java.awt.Color(255, 204, 204));
        jLabel56.setText("jLabel16");
        jLabel56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 110, 40));

        jLabel57.setText("jLabel16");
        jLabel57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 110, 40));

        jLabel58.setBackground(new java.awt.Color(204, 255, 255));
        jLabel58.setForeground(new java.awt.Color(255, 204, 204));
        jLabel58.setText("jLabel16");
        jLabel58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 110, 40));

        jLabel59.setBackground(new java.awt.Color(204, 255, 255));
        jLabel59.setForeground(new java.awt.Color(255, 204, 204));
        jLabel59.setText("jLabel16");
        jLabel59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 110, 40));

        jLabel60.setBackground(new java.awt.Color(204, 255, 255));
        jLabel60.setForeground(new java.awt.Color(255, 204, 204));
        jLabel60.setText("jLabel16");
        jLabel60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 110, 40));

        jLabel61.setBackground(new java.awt.Color(204, 255, 255));
        jLabel61.setForeground(new java.awt.Color(255, 204, 204));
        jLabel61.setText("jLabel16");
        jLabel61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 110, 40));

        jLabel62.setBackground(new java.awt.Color(204, 255, 255));
        jLabel62.setForeground(new java.awt.Color(255, 204, 204));
        jLabel62.setText("jLabel16");
        jLabel62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 110, 40));

        jLabel63.setBackground(new java.awt.Color(204, 255, 255));
        jLabel63.setForeground(new java.awt.Color(255, 204, 204));
        jLabel63.setText("jLabel16");
        jLabel63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 110, 40));

        jLabel64.setBackground(new java.awt.Color(204, 255, 255));
        jLabel64.setForeground(new java.awt.Color(255, 204, 204));
        jLabel64.setText("jLabel16");
        jLabel64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 110, 40));

        jLabel65.setText("jLabel16");
        jLabel65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSchedule.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelSchedule;
    private javax.swing.JLabel txtMonday8_9;
    // End of variables declaration//GEN-END:variables
}
