/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfaW;

/**
 *
 * @author wendy_6rrub
 */
public class StudentSchedule extends javax.swing.JPanel {

    /**
     * Creates new form StudentSchedule
     */
    public StudentSchedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSchedule = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jTextField69 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jTextField78 = new javax.swing.JTextField();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jTextField81 = new javax.swing.JTextField();
        jTextField82 = new javax.swing.JTextField();
        jTextField83 = new javax.swing.JTextField();
        jTextField84 = new javax.swing.JTextField();
        jTextField85 = new javax.swing.JTextField();
        jTextField86 = new javax.swing.JTextField();
        jTextField87 = new javax.swing.JTextField();
        jTextField88 = new javax.swing.JTextField();
        jTextField89 = new javax.swing.JTextField();
        jTextField90 = new javax.swing.JTextField();
        jTextField91 = new javax.swing.JTextField();
        jTextField92 = new javax.swing.JTextField();
        jTextField93 = new javax.swing.JTextField();
        jTextField94 = new javax.swing.JTextField();
        jTextField95 = new javax.swing.JTextField();
        jTextField96 = new javax.swing.JTextField();
        jTextField97 = new javax.swing.JTextField();
        jTextField98 = new javax.swing.JTextField();
        jTextField99 = new javax.swing.JTextField();

        panelSchedule.setBackground(new java.awt.Color(255, 255, 255));
        panelSchedule.setForeground(new java.awt.Color(51, 102, 0));
        panelSchedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("Lunes");
        panelSchedule.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText(" Martes");
        panelSchedule.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 0));
        jLabel3.setText("Miércoles");
        panelSchedule.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText(" Jueves");
        panelSchedule.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 0));
        jLabel5.setText("Viernes");
        panelSchedule.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 0));
        jLabel6.setText("05:00 pm");
        panelSchedule.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 0));
        jLabel7.setText("  8:00 am");
        panelSchedule.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 0));
        jLabel8.setText("  9:00 am");
        panelSchedule.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 0));
        jLabel9.setText("10:00 am");
        panelSchedule.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 0));
        jLabel10.setText("11:00 am");
        panelSchedule.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 102, 0));
        jLabel11.setText("12:00 pm");
        panelSchedule.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 102, 0));
        jLabel12.setText("01:00 pm");
        panelSchedule.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 102, 0));
        jLabel13.setText("02:00 pm");
        panelSchedule.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel14.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 102, 0));
        jLabel14.setText("03:00 pm");
        panelSchedule.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel15.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 102, 0));
        jLabel15.setText("04:00 pm");
        panelSchedule.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("jTextField1");
        jTextField2.setBorder(null);
        panelSchedule.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 110, 40));

        jTextField51.setEditable(false);
        jTextField51.setBackground(new java.awt.Color(204, 204, 204));
        jTextField51.setText("jTextField1");
        jTextField51.setBorder(null);
        panelSchedule.add(jTextField51, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 110, 40));

        jTextField52.setEditable(false);
        jTextField52.setBackground(new java.awt.Color(204, 204, 204));
        jTextField52.setText("jTextField1");
        jTextField52.setBorder(null);
        panelSchedule.add(jTextField52, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 110, 40));

        jTextField53.setEditable(false);
        jTextField53.setBackground(new java.awt.Color(204, 204, 204));
        jTextField53.setText("jTextField1");
        jTextField53.setBorder(null);
        panelSchedule.add(jTextField53, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 110, 40));

        jTextField54.setEditable(false);
        jTextField54.setBackground(new java.awt.Color(204, 204, 204));
        jTextField54.setText("jTextField1");
        jTextField54.setBorder(null);
        panelSchedule.add(jTextField54, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 110, 40));

        jTextField55.setEditable(false);
        jTextField55.setBackground(new java.awt.Color(204, 204, 204));
        jTextField55.setText("jTextField1");
        jTextField55.setBorder(null);
        panelSchedule.add(jTextField55, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 110, 40));

        jTextField56.setEditable(false);
        jTextField56.setBackground(new java.awt.Color(204, 204, 204));
        jTextField56.setText("jTextField1");
        jTextField56.setBorder(null);
        panelSchedule.add(jTextField56, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 110, 40));

        jTextField57.setEditable(false);
        jTextField57.setBackground(new java.awt.Color(204, 204, 204));
        jTextField57.setText("jTextField1");
        jTextField57.setBorder(null);
        panelSchedule.add(jTextField57, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 110, 40));

        jTextField58.setEditable(false);
        jTextField58.setBackground(new java.awt.Color(204, 204, 204));
        jTextField58.setText("jTextField1");
        jTextField58.setBorder(null);
        panelSchedule.add(jTextField58, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 110, 40));

        jTextField59.setEditable(false);
        jTextField59.setBackground(new java.awt.Color(204, 204, 204));
        jTextField59.setText("jTextField1");
        jTextField59.setBorder(null);
        panelSchedule.add(jTextField59, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 110, 40));

        jTextField60.setEditable(false);
        jTextField60.setBackground(new java.awt.Color(204, 204, 204));
        jTextField60.setText("jTextField1");
        jTextField60.setBorder(null);
        panelSchedule.add(jTextField60, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 110, 40));

        jTextField61.setEditable(false);
        jTextField61.setBackground(new java.awt.Color(204, 204, 204));
        jTextField61.setText("jTextField1");
        jTextField61.setBorder(null);
        panelSchedule.add(jTextField61, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 110, 40));

        jTextField62.setEditable(false);
        jTextField62.setBackground(new java.awt.Color(204, 204, 204));
        jTextField62.setText("jTextField1");
        jTextField62.setBorder(null);
        panelSchedule.add(jTextField62, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 110, 40));

        jTextField63.setEditable(false);
        jTextField63.setBackground(new java.awt.Color(204, 204, 204));
        jTextField63.setText("jTextField1");
        jTextField63.setBorder(null);
        panelSchedule.add(jTextField63, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 110, 40));

        jTextField64.setEditable(false);
        jTextField64.setBackground(new java.awt.Color(204, 204, 204));
        jTextField64.setText("jTextField1");
        jTextField64.setBorder(null);
        panelSchedule.add(jTextField64, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 110, 40));

        jTextField65.setEditable(false);
        jTextField65.setBackground(new java.awt.Color(204, 204, 204));
        jTextField65.setText("jTextField1");
        jTextField65.setBorder(null);
        panelSchedule.add(jTextField65, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 110, 40));

        jTextField66.setEditable(false);
        jTextField66.setBackground(new java.awt.Color(204, 204, 204));
        jTextField66.setText("jTextField1");
        jTextField66.setBorder(null);
        panelSchedule.add(jTextField66, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 110, 40));

        jTextField67.setEditable(false);
        jTextField67.setBackground(new java.awt.Color(204, 204, 204));
        jTextField67.setText("jTextField1");
        jTextField67.setBorder(null);
        panelSchedule.add(jTextField67, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 110, 40));

        jTextField68.setEditable(false);
        jTextField68.setBackground(new java.awt.Color(204, 204, 204));
        jTextField68.setText("jTextField1");
        jTextField68.setBorder(null);
        panelSchedule.add(jTextField68, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 110, 40));

        jTextField69.setEditable(false);
        jTextField69.setBackground(new java.awt.Color(204, 204, 204));
        jTextField69.setText("jTextField1");
        jTextField69.setBorder(null);
        panelSchedule.add(jTextField69, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 110, 40));

        jTextField70.setEditable(false);
        jTextField70.setBackground(new java.awt.Color(204, 204, 204));
        jTextField70.setText("jTextField1");
        jTextField70.setBorder(null);
        panelSchedule.add(jTextField70, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 110, 40));

        jTextField71.setEditable(false);
        jTextField71.setBackground(new java.awt.Color(204, 204, 204));
        jTextField71.setText("jTextField1");
        jTextField71.setBorder(null);
        panelSchedule.add(jTextField71, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 110, 40));

        jTextField72.setEditable(false);
        jTextField72.setBackground(new java.awt.Color(204, 204, 204));
        jTextField72.setText("jTextField1");
        jTextField72.setBorder(null);
        panelSchedule.add(jTextField72, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 110, 40));

        jTextField73.setEditable(false);
        jTextField73.setBackground(new java.awt.Color(204, 204, 204));
        jTextField73.setText("jTextField1");
        jTextField73.setBorder(null);
        panelSchedule.add(jTextField73, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 110, 40));

        jTextField74.setEditable(false);
        jTextField74.setBackground(new java.awt.Color(204, 204, 204));
        jTextField74.setText("jTextField1");
        jTextField74.setBorder(null);
        panelSchedule.add(jTextField74, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 110, 40));

        jTextField75.setEditable(false);
        jTextField75.setBackground(new java.awt.Color(204, 204, 204));
        jTextField75.setText("jTextField1");
        jTextField75.setBorder(null);
        panelSchedule.add(jTextField75, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 110, 40));

        jTextField76.setEditable(false);
        jTextField76.setBackground(new java.awt.Color(204, 204, 204));
        jTextField76.setText("jTextField1");
        jTextField76.setBorder(null);
        panelSchedule.add(jTextField76, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 110, 40));

        jTextField77.setEditable(false);
        jTextField77.setBackground(new java.awt.Color(204, 204, 204));
        jTextField77.setText("jTextField1");
        jTextField77.setBorder(null);
        panelSchedule.add(jTextField77, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 110, 40));

        jTextField78.setEditable(false);
        jTextField78.setBackground(new java.awt.Color(204, 204, 204));
        jTextField78.setText("jTextField1");
        jTextField78.setBorder(null);
        panelSchedule.add(jTextField78, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 110, 40));

        jTextField79.setEditable(false);
        jTextField79.setBackground(new java.awt.Color(204, 204, 204));
        jTextField79.setText("jTextField1");
        jTextField79.setBorder(null);
        panelSchedule.add(jTextField79, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 110, 40));

        jTextField80.setEditable(false);
        jTextField80.setBackground(new java.awt.Color(204, 204, 204));
        jTextField80.setText("jTextField1");
        jTextField80.setBorder(null);
        panelSchedule.add(jTextField80, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 110, 40));

        jTextField81.setEditable(false);
        jTextField81.setBackground(new java.awt.Color(204, 204, 204));
        jTextField81.setText("jTextField1");
        jTextField81.setBorder(null);
        panelSchedule.add(jTextField81, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 110, 40));

        jTextField82.setEditable(false);
        jTextField82.setBackground(new java.awt.Color(204, 204, 204));
        jTextField82.setText("jTextField1");
        jTextField82.setBorder(null);
        panelSchedule.add(jTextField82, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 110, 40));

        jTextField83.setEditable(false);
        jTextField83.setBackground(new java.awt.Color(204, 204, 204));
        jTextField83.setText("jTextField1");
        jTextField83.setBorder(null);
        panelSchedule.add(jTextField83, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 110, 40));

        jTextField84.setEditable(false);
        jTextField84.setBackground(new java.awt.Color(204, 204, 204));
        jTextField84.setText("jTextField1");
        jTextField84.setBorder(null);
        panelSchedule.add(jTextField84, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 110, 40));

        jTextField85.setEditable(false);
        jTextField85.setBackground(new java.awt.Color(204, 204, 204));
        jTextField85.setText("jTextField1");
        jTextField85.setBorder(null);
        panelSchedule.add(jTextField85, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 110, 40));

        jTextField86.setEditable(false);
        jTextField86.setBackground(new java.awt.Color(204, 204, 204));
        jTextField86.setText("jTextField1");
        jTextField86.setBorder(null);
        panelSchedule.add(jTextField86, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 110, 40));

        jTextField87.setEditable(false);
        jTextField87.setBackground(new java.awt.Color(204, 204, 204));
        jTextField87.setText("jTextField1");
        jTextField87.setBorder(null);
        panelSchedule.add(jTextField87, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 110, 40));

        jTextField88.setEditable(false);
        jTextField88.setBackground(new java.awt.Color(204, 204, 204));
        jTextField88.setText("jTextField1");
        jTextField88.setBorder(null);
        panelSchedule.add(jTextField88, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 110, 40));

        jTextField89.setEditable(false);
        jTextField89.setBackground(new java.awt.Color(204, 204, 204));
        jTextField89.setText("jTextField1");
        jTextField89.setBorder(null);
        panelSchedule.add(jTextField89, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 110, 40));

        jTextField90.setEditable(false);
        jTextField90.setBackground(new java.awt.Color(204, 204, 204));
        jTextField90.setText("jTextField1");
        jTextField90.setBorder(null);
        panelSchedule.add(jTextField90, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 110, 40));

        jTextField91.setEditable(false);
        jTextField91.setBackground(new java.awt.Color(204, 204, 204));
        jTextField91.setText("jTextField1");
        jTextField91.setBorder(null);
        panelSchedule.add(jTextField91, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 110, 40));

        jTextField92.setEditable(false);
        jTextField92.setBackground(new java.awt.Color(204, 204, 204));
        jTextField92.setText("jTextField1");
        jTextField92.setBorder(null);
        panelSchedule.add(jTextField92, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 110, 40));

        jTextField93.setEditable(false);
        jTextField93.setBackground(new java.awt.Color(204, 204, 204));
        jTextField93.setText("jTextField1");
        jTextField93.setBorder(null);
        panelSchedule.add(jTextField93, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 110, 40));

        jTextField94.setEditable(false);
        jTextField94.setBackground(new java.awt.Color(204, 204, 204));
        jTextField94.setText("jTextField1");
        jTextField94.setBorder(null);
        panelSchedule.add(jTextField94, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 110, 40));

        jTextField95.setEditable(false);
        jTextField95.setBackground(new java.awt.Color(204, 204, 204));
        jTextField95.setText("jTextField1");
        jTextField95.setBorder(null);
        panelSchedule.add(jTextField95, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 110, 40));

        jTextField96.setEditable(false);
        jTextField96.setBackground(new java.awt.Color(204, 204, 204));
        jTextField96.setText("jTextField1");
        jTextField96.setBorder(null);
        panelSchedule.add(jTextField96, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 110, 40));

        jTextField97.setEditable(false);
        jTextField97.setBackground(new java.awt.Color(204, 204, 204));
        jTextField97.setText("jTextField1");
        jTextField97.setBorder(null);
        panelSchedule.add(jTextField97, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 110, 40));

        jTextField98.setEditable(false);
        jTextField98.setBackground(new java.awt.Color(204, 204, 204));
        jTextField98.setText("jTextField1");
        jTextField98.setBorder(null);
        panelSchedule.add(jTextField98, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 110, 40));

        jTextField99.setEditable(false);
        jTextField99.setBackground(new java.awt.Color(204, 204, 204));
        jTextField99.setText("jTextField1");
        jTextField99.setBorder(null);
        panelSchedule.add(jTextField99, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField82;
    private javax.swing.JTextField jTextField83;
    private javax.swing.JTextField jTextField84;
    private javax.swing.JTextField jTextField85;
    private javax.swing.JTextField jTextField86;
    private javax.swing.JTextField jTextField87;
    private javax.swing.JTextField jTextField88;
    private javax.swing.JTextField jTextField89;
    private javax.swing.JTextField jTextField90;
    private javax.swing.JTextField jTextField91;
    private javax.swing.JTextField jTextField92;
    private javax.swing.JTextField jTextField93;
    private javax.swing.JTextField jTextField94;
    private javax.swing.JTextField jTextField95;
    private javax.swing.JTextField jTextField96;
    private javax.swing.JTextField jTextField97;
    private javax.swing.JTextField jTextField98;
    private javax.swing.JTextField jTextField99;
    private javax.swing.JPanel panelSchedule;
    // End of variables declaration//GEN-END:variables
}
