
package Interface;

import Controller.controller;
import Model.Courses;
import Model.CoursesDAO;
import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author wendy_6rrub
 */
public class AddCourse extends javax.swing.JFrame {

    /**
     * Creates new form AddCourse
     */
    public AddCourse() {
        initComponents();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        
    }

    
    public JButton getBtnAddCourse() {
        return btnAddCourse;
    }

    public void setBtnAddCourse(JButton btnAddCourse) {
        this.btnAddCourse = btnAddCourse;
    }

    public JComboBox<String> getComboAmount() {
        return comboAmount;
    }

    public void setComboAmount(JComboBox<String> comboAmount) {
        this.comboAmount = comboAmount;
    }

    public JComboBox<String> getComboArea() {
        return comboArea;
    }

    public void setComboArea(JComboBox<String> comboArea) {
        this.comboArea = comboArea;
    }

    public JComboBox<String> getComboDuration() {
        return comboDuration;
    }

    public void setComboDuration(JComboBox<String> comboDuration) {
        this.comboDuration = comboDuration;
    }

    public JComboBox<String> getComoMod() {
        return comoMod;
    }

    public void setComoMod(JComboBox<String> comoMod) {
        this.comoMod = comoMod;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JTextField getTxtCoursename() {
        return txtCoursename;
    }

    public void setTxtCoursename(JTextField txtCoursename) {
        this.txtCoursename = txtCoursename;
    }

    public JTextField getTxtDateE() {
        return txtDateE;
    }

    public void setTxtDateE(JTextField txtDateE) {
        this.txtDateE = txtDateE;
    }

    public JTextField getTxtDateO() {
        return txtDateO;
    }

    public void setTxtDateO(JTextField txtDateO) {
        this.txtDateO = txtDateO;
    }

    public JTextField getTxtInitials() {
        return txtInitials;
    }

    public void setTxtInitials(JTextField txtInitials) {
        this.txtInitials = txtInitials;
    }

    public JTextField getTxtSchedule() {
        return txtSchedule;
    }

    public void setTxtSchedule(JTextField txtSchedule) {
        this.txtSchedule = txtSchedule;
    }
    

    public String[] getCourseDetails() {
        String[] details = new String[9];
        
        details[0] = getTxtCoursename().getText();  // Nombre del curso
        details[1] = getTxtInitials().getText();    // Iniciales
        details[2] = getTxtSchedule().getText();    // Horario
        details[3] = getTxtDateO().getText();       // Fecha de inicio
        details[4] = getTxtDateE().getText();       // Fecha de fin
        details[5] = (String) getComoMod().getSelectedItem();  // Modo
        details[6] = (String) getComboArea().getSelectedItem(); // Área
        details[7] = getComboAmount().getSelectedItem().toString(); // Cantidad
        details[8] = (String) getComboDuration().getSelectedItem(); // Duración

        return details;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAddCourse = new javax.swing.JButton();
        txtInitials = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCoursename = new javax.swing.JTextField();
        comoMod = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboArea = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        comboDuration = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtSchedule = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDateE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDateO = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboAmount = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 232, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Agregar Curso");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 19, -1, -1));

        btnAddCourse.setText("Agregar");
        btnAddCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddCourseMouseClicked(evt);
            }
        });
        jPanel1.add(btnAddCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 435, 96, -1));

        txtInitials.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtInitials, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 91, 103, -1));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Sigla");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 95, -1, -1));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Nombre del curso");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, 20));

        txtCoursename.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtCoursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 210, -1));

        comoMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presencial", "Bimodal", "Virtual" }));
        jPanel1.add(comoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 110, -1));

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Modalidad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Area de especialización");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        comboArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arte", "Actividad física", "Salud y Bienestar", "Tecnología", "Medio ambiente" }));
        jPanel1.add(comboArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 120, -1));

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Duración (en meses)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        comboDuration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 mes", "2 meses", "3 meses", "4 meses", "5 meses", "6 meses", "7 meses", "8 meses" }));
        jPanel1.add(comboDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Horario [Días - horas]");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        txtSchedule.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 360, -1));

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Fecha de inicio");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        txtDateE.setBackground(new java.awt.Color(255, 255, 255));
        txtDateE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateEFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateEFocusLost(evt);
            }
        });
        jPanel1.add(txtDateE, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 130, -1));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Fecha finalización");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        txtDateO.setBackground(new java.awt.Color(255, 255, 255));
        txtDateO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateOFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateOFocusLost(evt);
            }
        });
        jPanel1.add(txtDateO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 130, -1));

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Cantidad estudiantes");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        comboAmount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "12", "14", "16", "18", "20", "22", "24", "26", "28", "30" }));
        jPanel1.add(comboAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCourseMouseClicked
            controller control = new controller();
    String name = getTxtCoursename().getText();
    String ini = getTxtInitials().getText();
    String sch = getTxtSchedule().getText();
    String ope = getTxtDateO().getText();
    String end = getTxtDateE().getText();
    String moda = (String) getComoMod().getSelectedItem();
    String area = (String) getComboArea().getSelectedItem();
    int quant = Integer.parseInt(getComboAmount().getSelectedItem().toString());
    String dur = (String) getComboDuration().getSelectedItem();

        try {
            control.addCourses(name, ini, sch, ope, end, moda, area, quant, dur);
        } catch (ParseException ex) {
            Logger.getLogger(AddCourse.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAddCourseMouseClicked

    private void txtDateOFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateOFocusGained
        if (txtDateO.getText().equals("yyyy-MM-dd")){
            txtDateO.setText("");
            txtDateO.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtDateOFocusGained

    private void txtDateOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateOFocusLost
        if (txtDateO.getText().equals("")) {
            txtDateO.setText("yyyy-MM-dd");
            txtDateO.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtDateOFocusLost

    private void txtDateEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateEFocusGained
       if (txtDateE.getText().equals("yyyy-MM-dd")){
            txtDateE.setText("");
            txtDateE.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtDateEFocusGained

    private void txtDateEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateEFocusLost
        if (txtDateE.getText().equals("")) {
            txtDateE.setText("yyyy-MM-dd");
            txtDateE.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txtDateEFocusLost



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddCourse;
    public javax.swing.JComboBox<String> comboAmount;
    public javax.swing.JComboBox<String> comboArea;
    public javax.swing.JComboBox<String> comboDuration;
    public javax.swing.JComboBox<String> comoMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtCoursename;
    public javax.swing.JTextField txtDateE;
    public javax.swing.JTextField txtDateO;
    public javax.swing.JTextField txtInitials;
    public javax.swing.JTextField txtSchedule;
    // End of variables declaration//GEN-END:variables
}
