/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
/**
 *
 * @author franc
 */
public class AdmistratorInterface extends javax.swing.JFrame {

   
    /**
     * Creates new form AdmistratorInterface
     */
    public AdmistratorInterface() {
        initComponents();
         
        
        if (Panel != null) {
        //panel trasparente 
        Panel.setBackground(new Color(255, 255, 255, 100)); // Blanco con 100 de opacidad 
        Panel.setOpaque(true); 
       
       
    }   
    }
    
    //metodo para poder mostrar las clases dentro del panel
   public void ShowPanel(javax.swing.JPanel p) {
    p.setSize(709, 640); 
    p.setLocation(0, 0);
    Content.removeAll();
    Content.add(p, BorderLayout.CENTER);
    Content.revalidate();
    Content.repaint();
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        RegisterPeople = new javax.swing.JLabel();
        ManageRegistrations = new javax.swing.JLabel();
        ManageCourses = new javax.swing.JLabel();
        ManageStaff = new javax.swing.JLabel();
        HistoryStudents = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        PerfilUser = new javax.swing.JLabel();
        NameUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        RegisterPeople.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        RegisterPeople.setForeground(new java.awt.Color(87, 73, 98));
        RegisterPeople.setText(" Registrar Personas");
        RegisterPeople.setToolTipText("");
        RegisterPeople.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterPeopleMouseClicked(evt);
            }
        });

        ManageRegistrations.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        ManageRegistrations.setForeground(new java.awt.Color(87, 73, 98));
        ManageRegistrations.setText(" Gestionar Incripciones");
        ManageRegistrations.setToolTipText("");

        ManageCourses.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        ManageCourses.setForeground(new java.awt.Color(87, 73, 98));
        ManageCourses.setText(" Gestionar Cursos");
        ManageCourses.setToolTipText("");

        ManageStaff.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        ManageStaff.setForeground(new java.awt.Color(87, 73, 98));
        ManageStaff.setText(" Gestionar Personal");
        ManageStaff.setToolTipText("");
        ManageStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageStaffMouseClicked(evt);
            }
        });

        HistoryStudents.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        HistoryStudents.setForeground(new java.awt.Color(87, 73, 98));
        HistoryStudents.setText("Historial Estudiantes");
        HistoryStudents.setToolTipText("");
        HistoryStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoryStudentsMouseClicked(evt);
            }
        });

        Content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        Exit.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        Exit.setForeground(new java.awt.Color(87, 73, 98));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-logout-24.png"))); // NOI18N
        Exit.setText("Cerrar Sesion ");
        Exit.setToolTipText("");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        PerfilUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-user-48 (1).png"))); // NOI18N
        PerfilUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PerfilUserMouseClicked(evt);
            }
        });

        NameUser.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        NameUser.setForeground(new java.awt.Color(87, 73, 98));
        NameUser.setText("     Nombre Usuario");
        NameUser.setToolTipText("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/LOGOOO.png"))); // NOI18N

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ManageCourses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RegisterPeople, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HistoryStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ManageRegistrations, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                    .addComponent(NameUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManageStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(PerfilUser))
                    .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(PerfilUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameUser)
                .addGap(50, 50, 50)
                .addComponent(HistoryStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageRegistrations, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(PanelLayout.createSequentialGroup()
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 880, 640));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/datachef_gradation_1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 990, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitMouseClicked

    private void ManageStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageStaffMouseClicked
        ManageStaff manage = new ManageStaff ();
        ShowPanel(manage);
    }//GEN-LAST:event_ManageStaffMouseClicked

    private void PerfilUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerfilUserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilUserMouseClicked

    private void HistoryStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryStudentsMouseClicked
        ViewHistory his = new ViewHistory ();
        ShowPanel(his);
                           
    }//GEN-LAST:event_HistoryStudentsMouseClicked

    private void RegisterPeopleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterPeopleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterPeopleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmistratorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmistratorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmistratorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmistratorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmistratorInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel HistoryStudents;
    private javax.swing.JLabel ManageCourses;
    private javax.swing.JLabel ManageRegistrations;
    private javax.swing.JLabel ManageStaff;
    private javax.swing.JLabel NameUser;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel PerfilUser;
    private javax.swing.JLabel RegisterPeople;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
