/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import Controller.ControllerFacilitators;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author franc
 */
public class ManageStaff extends javax.swing.JPanel {

    private ControllerFacilitators controller;

    /**
     * Creates new form ManageStaff
     */
    public ManageStaff() {
        initComponents();

        controller = new ControllerFacilitators(this);

        controller = new ControllerFacilitators(this);

        teachers.addActionListener(e -> {
            String searchTerm = Search1.getText().trim();
            controller.loadTeachersData(TeacStu, searchTerm);
        });

        students.addActionListener(e -> {
            String searchTerm = Search1.getText().trim();
            controller.loadStudentsData(TeacStu, searchTerm);
        });
        if (PanelMS != null) {
            //panel trasparente 
            PanelMS.setBackground(new Color(195, 152, 242, 47)); // Morado con 70 de opacidad 
            PanelMS.setOpaque(true);
        }
    }
      public int getSelectedPersonId() {
        int selectedRow = TeacStu.getSelectedRow();
        if (selectedRow != -1) {
            return (int) TeacStu.getValueAt(selectedRow, 0); // Asumiendo que el ID está en la primera columna
        }
        return -1; // No hay fila seleccionada
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelM = new javax.swing.JPanel();
        PanelMS = new javax.swing.JPanel();
        Search1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TeacStu = new javax.swing.JTable();
        Erase = new javax.swing.JLabel();
        Modify = new javax.swing.JLabel();
        teachers = new javax.swing.JButton();
        students = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelM.setBackground(new java.awt.Color(255, 255, 255));
        PanelM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMS.setBackground(new java.awt.Color(195, 152, 242));
        PanelMS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Search1.setBackground(new java.awt.Color(255, 255, 255));
        Search1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        Search1.setForeground(new java.awt.Color(87, 73, 98));
        Search1.setBorder(null);
        Search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search1ActionPerformed(evt);
            }
        });
        PanelMS.add(Search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 580, 40));

        TeacStu.setBackground(new java.awt.Color(255, 255, 255));
        TeacStu.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 10)); // NOI18N
        TeacStu.setForeground(new java.awt.Color(87, 73, 98));
        TeacStu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TeacStu.setSelectionBackground(new java.awt.Color(234, 203, 234));
        TeacStu.setSelectionForeground(new java.awt.Color(87, 73, 98));
        jScrollPane1.setViewportView(TeacStu);

        PanelMS.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 131, 630, 400));

        Erase.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        Erase.setForeground(new java.awt.Color(87, 73, 98));
        Erase.setText("Eliminar");
        Erase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EraseMouseClicked(evt);
            }
        });
        PanelMS.add(Erase, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 60, 20));

        Modify.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        Modify.setForeground(new java.awt.Color(87, 73, 98));
        Modify.setText("Modificar Estudiante");
        Modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifyMouseClicked(evt);
            }
        });
        PanelMS.add(Modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 150, 20));

        teachers.setBackground(new java.awt.Color(225, 225, 255));
        teachers.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        teachers.setText("Profesores");
        teachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachersActionPerformed(evt);
            }
        });
        PanelMS.add(teachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 310, -1));

        students.setBackground(new java.awt.Color(225, 225, 255));
        students.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        students.setText("Estudiantes");
        students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentsActionPerformed(evt);
            }
        });
        PanelMS.add(students, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 310, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-search-more-24.png"))); // NOI18N
        PanelMS.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        PanelM.add(PanelMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 670, 600));

        add(PanelM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void Search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search1ActionPerformed

    private void ModifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyMouseClicked
         int selectedRow = TeacStu.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una fila primero.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) TeacStu.getModel();

        // Determinar el tipo de persona según el contenido de la tabla
        String tableType = model.getColumnName(0).equals("ID Estudiante") ? "Estudiante" : "Facilitador";

        // Abrir la ventana correspondiente sin cargar datos
        if (tableType.equals("Estudiante")) {
            ModifyStudents modifyStudentsDialog = new ModifyStudents(this);
            showAsDialog(modifyStudentsDialog, "Modificar Estudiante");
        } 
    }//GEN-LAST:event_ModifyMouseClicked
    private void showAsDialog(javax.swing.JPanel panel, String title) {
    javax.swing.JDialog dialog = new javax.swing.JDialog();
    dialog.setTitle(title);
    dialog.setModal(true); // Hacerlo modal
    dialog.setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
    dialog.getContentPane().add(panel);
    dialog.pack();
    dialog.setLocationRelativeTo(this); // Centrar la ventana respecto al panel principal
    dialog.setVisible(true);
}
    private void EraseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EraseMouseClicked
        int selectedRow = TeacStu.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una fila primero.");
            return;
        }

        String id = TeacStu.getValueAt(selectedRow, 0).toString();
        String nombre = TeacStu.getValueAt(selectedRow, 2).toString();
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea eliminar a " + nombre + " (ID: " + id + ")?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            controller.deleteRecord(id, TeacStu);
        }
    }//GEN-LAST:event_EraseMouseClicked

    private void teachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachersActionPerformed

    private void studentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Erase;
    private javax.swing.JLabel Modify;
    private javax.swing.JPanel PanelM;
    private javax.swing.JPanel PanelMS;
    private javax.swing.JTextField Search1;
    public javax.swing.JTable TeacStu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton students;
    private javax.swing.JButton teachers;
    // End of variables declaration//GEN-END:variables
}
