/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package Interface;

import java.awt.Color;

/**
 *
 * @author wendy_6rrub
 */
public class ManageInscriptions extends javax.swing.JPanel {

    /** Creates new form ManageInscriptions */
    public ManageInscriptions() {
        initComponents();
        
        if (TableView != null) {
            TableView.setBackground(new Color(234,203,234, 75));
            TableView.setOpaque(true);
        }
        
        
jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
    @Override
    public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent e) {
        TableView.getParent().repaint();
    }

    @Override
    public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent e) {
        TableView.getParent().repaint();
    }

    @Override
    public void popupMenuCanceled(javax.swing.event.PopupMenuEvent e) {
        TableView.getParent().repaint();
    }
});
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Table1 = new javax.swing.JPanel();
        TableView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Search2 = new javax.swing.JTextField();
        btnDeleteIns = new javax.swing.JButton();
        btnAddIns = new javax.swing.JButton();
        btnEditIns = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        Table1.setBackground(new java.awt.Color(255, 255, 255));
        Table1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableView.setBackground(new java.awt.Color(248, 222, 255));
        TableView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(87, 73, 98));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(234, 203, 234));
        jTable1.setSelectionForeground(new java.awt.Color(87, 73, 98));
        jScrollPane1.setViewportView(jTable1);

        TableView.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 380));

        jComboBox2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(87, 73, 98));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TableView.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-search-more-24.png"))); // NOI18N
        TableView.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        Search2.setBackground(new java.awt.Color(255, 255, 255));
        Search2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        Search2.setForeground(new java.awt.Color(87, 73, 98));
        Search2.setBorder(null);
        TableView.add(Search2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 370, 40));

        btnDeleteIns.setText("Eliminar");
        TableView.add(btnDeleteIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 140, 50));

        btnAddIns.setText("Nueva Inscripción");
        TableView.add(btnAddIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 140, 50));

        btnEditIns.setText("Editar");
        TableView.add(btnEditIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 140, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        TableView.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 410, 380));

        Table1.add(TableView, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Table1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Table1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Search2;
    private javax.swing.JPanel Table1;
    private javax.swing.JPanel TableView;
    private javax.swing.JButton btnAddIns;
    private javax.swing.JButton btnDeleteIns;
    private javax.swing.JButton btnEditIns;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
