
package Interface;

import java.awt.Color;

/**
 *
 * @author wendy_6rrub
 */
public class ManageCourse extends javax.swing.JPanel {

    /**
     * Creates new form ManageCourse
     */
    public ManageCourse() {
        initComponents();
        
          if (panelCourses != null) {
            panelCourses.setBackground(new Color(234,203,234, 75));
            panelCourses.setOpaque(true);
        }
          
                 
comboCourses.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
    @Override
    public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent e) {
        panelCourses.getParent().repaint();
    }

    @Override
    public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent e) {
        panelCourses.getParent().repaint();
    }

    @Override
    public void popupMenuCanceled(javax.swing.event.PopupMenuEvent e) {
        panelCourses.getParent().repaint();
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCourses = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddCourse = new javax.swing.JButton();
        btnEditCourse = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();
        comboCourses = new javax.swing.JComboBox<>();
        searchButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelCourses.setBackground(new java.awt.Color(255, 211, 255));
        panelCourses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panelCourses.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 520, 40));

        jTable1.setForeground(new java.awt.Color(87, 73, 98));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sigla", "Curso", "Modalidad", "Cant. estudiantes", "Area", "Horario", "Duración", "Fecha inicio", "Fecha fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(234, 203, 234));
        jTable1.setSelectionForeground(new java.awt.Color(87, 73, 98));
        jScrollPane1.setViewportView(jTable1);

        panelCourses.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 590, 390));

        btnAddCourse.setText("Agregar");
        btnAddCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddCourseMouseClicked(evt);
            }
        });
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });
        panelCourses.add(btnAddCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 90, -1));

        btnEditCourse.setText("Editar");
        btnEditCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditCourseMouseClicked(evt);
            }
        });
        panelCourses.add(btnEditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 90, -1));

        btnDeleteCourse.setText("Eliminar");
        panelCourses.add(btnDeleteCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 120, 90, -1));

        comboCourses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Arte", "Actividad física", "Salud y Bienestar", "Tecnología", "Medio ambiente" }));
        comboCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCoursesActionPerformed(evt);
            }
        });
        panelCourses.add(comboCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 120, -1));

        searchButton1.setBackground(new java.awt.Color(204, 204, 255));
        searchButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-search-more-24.png"))); // NOI18N
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });
        panelCourses.add(searchButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void comboCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCoursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCoursesActionPerformed

    private void btnAddCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCourseMouseClicked
        AddCourse ac = new AddCourse();
        ac.setVisible(true);
    }//GEN-LAST:event_btnAddCourseMouseClicked

    private void btnEditCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourseMouseClicked
        EditCourses ec = new EditCourses();
        ec.setVisible(true);
    }//GEN-LAST:event_btnEditCourseMouseClicked

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnEditCourse;
    private javax.swing.JComboBox<String> comboCourses;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelCourses;
    private javax.swing.JButton searchButton1;
    // End of variables declaration//GEN-END:variables
}
