/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import Controller.ControllerFacilitators;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author franc
 */
public class ManageStaff extends javax.swing.JPanel {

    private ControllerFacilitators controller;

    /**
     * Creates new form ManageStaff
     */
    public ManageStaff() {
        initComponents();

        controller = new ControllerFacilitators(this);

        // Configura los listeners de los botones
        teachers.addActionListener(e -> controller.loadTeachersData(TeacStu));
        students.addActionListener(e -> controller.loadStudentsData(TeacStu));

        if (PanelMS != null) {
            //panel trasparente 
            PanelMS.setBackground(new Color(195, 152, 242, 47)); // Morado con 70 de opacidad 
            PanelMS.setOpaque(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelM = new javax.swing.JPanel();
        PanelMS = new javax.swing.JPanel();
        Search = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TeacStu = new javax.swing.JTable();
        Erase = new javax.swing.JLabel();
        Modify = new javax.swing.JLabel();
        teachers = new javax.swing.JButton();
        students = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelM.setBackground(new java.awt.Color(255, 255, 255));
        PanelM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMS.setBackground(new java.awt.Color(195, 152, 242));
        PanelMS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-search-more-24.png"))); // NOI18N
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
        });
        PanelMS.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 30, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(87, 73, 98));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        PanelMS.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 560, 40));

        TeacStu.setBackground(new java.awt.Color(255, 255, 255));
        TeacStu.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 10)); // NOI18N
        TeacStu.setForeground(new java.awt.Color(87, 73, 98));
        TeacStu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TeacStu.setSelectionBackground(new java.awt.Color(234, 203, 234));
        TeacStu.setSelectionForeground(new java.awt.Color(87, 73, 98));
        jScrollPane1.setViewportView(TeacStu);

        PanelMS.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 161, 630, 390));

        Erase.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        Erase.setForeground(new java.awt.Color(87, 73, 98));
        Erase.setText("Eliminar");
        Erase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EraseMouseClicked(evt);
            }
        });
        PanelMS.add(Erase, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 60, 20));

        Modify.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        Modify.setForeground(new java.awt.Color(87, 73, 98));
        Modify.setText("Modificar");
        Modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifyMouseClicked(evt);
            }
        });
        PanelMS.add(Modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 70, 20));

        teachers.setBackground(new java.awt.Color(204, 204, 255));
        teachers.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        teachers.setText("Profesores");
        teachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachersActionPerformed(evt);
            }
        });
        PanelMS.add(teachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 150, -1));

        students.setBackground(new java.awt.Color(204, 204, 255));
        students.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        students.setText("Estudiantes");
        students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentsActionPerformed(evt);
            }
        });
        PanelMS.add(students, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 100, 150, -1));

        PanelM.add(PanelMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 670, 600));

        add(PanelM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchMouseClicked

    private void ModifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyMouseClicked

    private void EraseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EraseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EraseMouseClicked

    private void teachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachersActionPerformed

    private void studentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Erase;
    private javax.swing.JLabel Modify;
    private javax.swing.JPanel PanelM;
    private javax.swing.JPanel PanelMS;
    private javax.swing.JLabel Search;
    public javax.swing.JTable TeacStu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton students;
    private javax.swing.JButton teachers;
    // End of variables declaration//GEN-END:variables
}
