/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import Controller.ControllerFacilitators;
import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class ModifyStudents extends javax.swing.JPanel {
private javax.swing.JDialog dialog;
    private ManageStaff manageStaff;

    /**
     * Creates new form Modify
     */
    public ModifyStudents(ManageStaff manageStaff) {
        this.manageStaff = manageStaff;
        this.dialog = dialog;
        initComponents();
        loadMaritalStatusOptions();
        Save.addActionListener(this::SaveActionPerformed);

    }

    private void loadMaritalStatusOptions() {
        maritalStatus.addItem("Soltero");
        maritalStatus.addItem("Casado");
        maritalStatus.addItem("Divorciado");
        maritalStatus.addItem("Viudo");
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        district = new javax.swing.JTextField();
        canton = new javax.swing.JTextField();
        province = new javax.swing.JTextField();
        phone2 = new javax.swing.JTextField();
        specialNeed = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        phone1 = new javax.swing.JTextField();
        maritalStatus = new javax.swing.JComboBox<>();
        Lastname2 = new javax.swing.JTextField();
        Lastname1 = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        district.setBackground(new java.awt.Color(255, 255, 255));
        district.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        district.setForeground(new java.awt.Color(87, 73, 98));
        district.setBorder(null);
        add(district, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 150, -1));

        canton.setBackground(new java.awt.Color(255, 255, 255));
        canton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        canton.setForeground(new java.awt.Color(87, 73, 98));
        canton.setBorder(null);
        add(canton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 150, -1));

        province.setBackground(new java.awt.Color(255, 255, 255));
        province.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        province.setForeground(new java.awt.Color(87, 73, 98));
        province.setBorder(null);
        add(province, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 150, -1));

        phone2.setBackground(new java.awt.Color(255, 255, 255));
        phone2.setForeground(new java.awt.Color(87, 73, 98));
        phone2.setBorder(null);
        add(phone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, -1));

        specialNeed.setBackground(new java.awt.Color(255, 255, 255));
        specialNeed.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        specialNeed.setForeground(new java.awt.Color(87, 73, 98));
        specialNeed.setBorder(null);
        add(specialNeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 270, 70));

        gender.setBackground(new java.awt.Color(255, 255, 255));
        gender.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        gender.setForeground(new java.awt.Color(87, 73, 98));
        gender.setBorder(null);
        add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 100, -1));

        phone1.setBackground(new java.awt.Color(255, 255, 255));
        phone1.setForeground(new java.awt.Color(87, 73, 98));
        phone1.setBorder(null);
        add(phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 210, -1));

        maritalStatus.setBackground(new java.awt.Color(255, 255, 255));
        maritalStatus.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        maritalStatus.setForeground(new java.awt.Color(87, 73, 98));
        maritalStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(maritalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 140, -1));

        Lastname2.setBackground(new java.awt.Color(255, 255, 255));
        Lastname2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        Lastname2.setForeground(new java.awt.Color(87, 73, 98));
        Lastname2.setBorder(null);
        add(Lastname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, -1));

        Lastname1.setBackground(new java.awt.Color(255, 255, 255));
        Lastname1.setForeground(new java.awt.Color(87, 73, 98));
        Lastname1.setBorder(null);
        add(Lastname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, -1));

        Name.setBackground(new java.awt.Color(255, 255, 255));
        Name.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        Name.setForeground(new java.awt.Color(87, 73, 98));
        Name.setBorder(null);
        add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, -1));

        Save.setBackground(new java.awt.Color(255, 255, 255));
        Save.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        Save.setForeground(new java.awt.Color(87, 73, 98));
        Save.setText("Guardar");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 200, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/LOGOOO.png"))); // NOI18N
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(87, 73, 98));
        jLabel11.setText("Necesidad Especial:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(87, 73, 98));
        jLabel10.setText("Distrito");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(87, 73, 98));
        jLabel14.setText("Estado Civil:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(87, 73, 98));
        jLabel13.setText("Genero:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(87, 73, 98));
        jLabel9.setText("Canton");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(87, 73, 98));
        jLabel8.setText("Provincia");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(87, 73, 98));
        jLabel7.setText("Direccion:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(87, 73, 98));
        jLabel6.setText("Telefono Secundario:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(87, 73, 98));
        jLabel5.setText("Telefono Principal:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(87, 73, 98));
        jLabel4.setText("Segundo Apellido:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(87, 73, 98));
        jLabel3.setText("Primer apellido:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(87, 73, 98));
        jLabel2.setText("Ingrese nuevo nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, 20));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/datachef_gradation_1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 600, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
       int idEstudiante = manageStaff.getSelectedPersonId();
        if (idEstudiante == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un estudiante de la tabla.");
            return;
        }

        // Llamar al controlador para actualizar los datos
        ControllerFacilitators controller = new ControllerFacilitators(manageStaff);
        controller.updateStudentData(idEstudiante, Name.getText(), Lastname1.getText(),
                Lastname2.getText(), phone1.getText(), phone2.getText(), province.getText(),
                canton.getText(), district.getText(), gender.getText(),
                specialNeed.getText(), maritalStatus.getSelectedItem().toString());
    }//GEN-LAST:event_SaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Lastname1;
    private javax.swing.JTextField Lastname2;
    private javax.swing.JTextField Name;
    private javax.swing.JButton Save;
    private javax.swing.JTextField canton;
    private javax.swing.JTextField district;
    private javax.swing.JTextField gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> maritalStatus;
    private javax.swing.JTextField phone1;
    private javax.swing.JTextField phone2;
    private javax.swing.JTextField province;
    private javax.swing.JTextField specialNeed;
    // End of variables declaration//GEN-END:variables

}
