/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import Controller.ControllerHistory;
import java.awt.Color;

/**
 *
 * @author franc
 */
public class ViewHistory extends javax.swing.JPanel {

    private ControllerHistory controller;

    /**
     * Creates new form ViewHistory
     */
    public ViewHistory() {
        initComponents();
        controller = new ControllerHistory(this);

        searchButton1.addActionListener(e -> {
            String searchTerm = Search2.getText();
            String course = (String) ComboCourses.getSelectedItem();
            controller.loadHistoryData(TablaH, searchTerm, course);
        });

        ComboCourses.addActionListener(e -> {
            String searchTerm = Search2.getText();
            String course = (String) ComboCourses.getSelectedItem();
            controller.loadHistoryData(TablaH, searchTerm, course);
        });

        controller.loadHistoryData(TablaH, null, null);

        controller.loadCourses(ComboCourses);

        ComboCourses.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            @Override
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent e) {
                TableView.getParent().repaint();
            }

            @Override
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent e) {
                TableView.getParent().repaint();
            }

            @Override
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent e) {
                TableView.getParent().repaint();
            }
        });

        if (TableView != null) {
            TableView.setBackground(new Color(195, 152, 242, 47));
            TableView.setOpaque(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Table1 = new javax.swing.JPanel();
        TableView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaH = new javax.swing.JTable();
        ComboCourses = new javax.swing.JComboBox<>();
        Search2 = new javax.swing.JTextField();
        searchButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        Table1.setBackground(new java.awt.Color(255, 255, 255));
        Table1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableView.setBackground(new java.awt.Color(195, 152, 242));
        TableView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaH.setBackground(new java.awt.Color(255, 255, 255));
        TablaH.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 10)); // NOI18N
        TablaH.setForeground(new java.awt.Color(87, 73, 98));
        TablaH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaH.setSelectionBackground(new java.awt.Color(234, 203, 234));
        TablaH.setSelectionForeground(new java.awt.Color(87, 73, 98));
        jScrollPane1.setViewportView(TablaH);

        TableView.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 630, 380));

        ComboCourses.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        ComboCourses.setForeground(new java.awt.Color(87, 73, 98));
        ComboCourses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCoursesActionPerformed(evt);
            }
        });
        TableView.add(ComboCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 230, -1));

        Search2.setBackground(new java.awt.Color(255, 255, 255));
        Search2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        Search2.setForeground(new java.awt.Color(87, 73, 98));
        Search2.setBorder(null);
        TableView.add(Search2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 570, 40));

        searchButton1.setBackground(new java.awt.Color(204, 204, 255));
        searchButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-search-more-24.png"))); // NOI18N
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });
        TableView.add(searchButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        Table1.add(TableView, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 670, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Table1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Table1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComboCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCoursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCoursesActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCourses;
    private javax.swing.JTextField Search2;
    public javax.swing.JTable TablaH;
    private javax.swing.JPanel Table1;
    private javax.swing.JPanel TableView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton1;
    // End of variables declaration//GEN-END:variables
}
